package edu.pitt.sis.exp.educvideos.entities;

/**
 * Domain generated by hbm2java
 */
public class Keyword implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String entity;
	private Integer entityId;
	private String keyword;
	
	public Keyword(){}
	
	public Keyword(String entity, Integer entityId, String keyword){
		this.setEntity(entity);
		this.setEntityId(entityId);
		this.setKeyword(keyword);
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEntity() {
		return entity;
	}

	public void setEntity(String entity) {
		this.entity = entity;
	}

	public Integer getEntityId() {
		return entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	public String getKeyword() {
		return keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

}
