package edu.pitt.sis.exp.educvideos.entities;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Segment generated by hbm2java
 */
public class Segment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private String name;
	private String title;
	private Video video;
	private Integer startTime;
	private Integer endTime;
	private Topic topic;
	private String description;
	private User author;
	private String version;
	private Date created;
	private Date modified;
	private String url;
	private Set<UserActivity> userActivities = new HashSet<UserActivity>(0);

	public Segment() {
	}

	public Segment(String name, String title, Video video, Integer startTime,
			Integer endTime, Topic topic, String description, User author,
			String version, Date created, Date modified, String url) {
		this.setName(name);
		this.setTitle(title);
		this.setVideo(video);
		this.setStartTime(startTime);
		this.setEndTime(endTime);
		this.setTopic(topic);
		this.setDescription(description);
		this.setAuthor(author);
		this.setVersion(version);
		this.setCreated(created);
		this.setModified(modified);
		this.setUrl(url);
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Video getVideo() {
		return video;
	}

	public void setVideo(Video video) {
		this.video = video;
	}

	public Integer getStartTime() {
		return startTime;
	}

	public void setStartTime(Integer startTime) {
		this.startTime = startTime;
	}

	public Integer getEndTime() {
		return endTime;
	}

	public void setEndTime(Integer endTime) {
		this.endTime = endTime;
	}

	public Topic getTopic() {
		return topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public User getAuthor() {
		return author;
	}

	public void setAuthor(User author) {
		this.author = author;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getModified() {
		return modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Set<UserActivity> getUserActivities() {
		return userActivities;
	}

	public void setUserActivities(Set<UserActivity> userActivities) {
		this.userActivities = userActivities;
	}
}
