package edu.pitt.sis.exp.educvideos.entities;

import java.util.HashSet;
import java.util.Set;

/**
 * Video generated by hbm2java
 */
public class Video implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private String title;
	private String youtubeId;
	private Set<Bookmark> bookmarks = new HashSet<Bookmark>(0);
	private Set<Segment> segments = new HashSet<Segment>(0);
	
	public Video(){}
	
	public Video(String name, String title, String youtubeId){
		this.setTitle(title);
		this.setYoutubeId(youtubeId);
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getYoutubeId() {
		return youtubeId;
	}

	public void setYoutubeId(String youtubeId) {
		this.youtubeId = youtubeId;
	}

	public Set<Bookmark> getBookmarks() {
		return bookmarks;
	}

	public void setBookmarks(Set<Bookmark> bookmarks) {
		this.bookmarks = bookmarks;
	}

	public Set<Segment> getSegments() {
		return segments;
	}

	public void setSegments(Set<Segment> segments) {
		this.segments = segments;
	}
	
}
